# Site
name: My Blog With Jekyll
description: Share knowlege about - programme language, health, books, travel, Vietnam history...
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
baseurl: 
email: 'ducna.tuy.tam.so.duc@gmail.com'
google_analytics: ''
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  blackeye68:
    name: DucNA
    display_name: blackeye68
    base_theme: free Affiliates Theme on Jekyllthemes.io
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: ducna.tuy.tam.so.duc@gmail.com
    web: https://www.sharetobetter.org/
    twitter: https://twitter.com/blackeye681
    description: "A my blog about share knowledge. My Blog build on base-theme Affiliates of Wowthemesnet Author"

# Plugins
plugins: 
  - jekyll-paginate  # plugin phân trang
  - jekyll-relative-links # plugin tạo link trực tiếp trên github pages
  #- jekyll-archives # plugin archive nhưng ko hoạt động tốt trên github pages
    

# Relative-links plugin
plugins:
  - jekyll-redirect-from
  
# Category
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge



